version: "3.8"

services:
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:8080"
  #   depends_on:
  #     - db
  #   environment:
  #     - DB_HOST=localhost
  #     - DB_PORT=5432
  #     - DB_USER=postgres
  #     - DB_PASSWORD=1234
  #     - DB_NAME=store-inventory
  #     - DB_URL=jdbc:postgresql://localhost:5432/store-inventory

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: store-inventory
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
